pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = "sharonba"
        FRONTEND_IMAGE = "${DOCKER_REGISTRY}/url-shortener-frontend"
        BACKEND_IMAGE  = "${DOCKER_REGISTRY}/url-shortener-backend"
        TF_DIR = 'terraform'
    }

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Select deployment environment')
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init & Workspace') {
            steps {
                withCredentials([file(credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {
                    dir("${TF_DIR}") {
                        sh 'terraform init'
                        sh "terraform workspace select ${params.ENVIRONMENT} || terraform workspace new ${params.ENVIRONMENT}"
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([file(credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {
                    dir("${TF_DIR}") {
                        sh 'terraform apply -auto-approve'
                        script {
                            env.DEPLOYED_NS = sh(script: 'terraform output -raw deployed_namespace', returnStdout: true).trim()
                        }
                    }
                }
            }
        }

        stage('Build Images') {
            steps {
                script {
                    def gitSha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    env.TAG = "${BUILD_NUMBER}-${gitSha}"
                    
                    sh "docker build -t ${FRONTEND_IMAGE}:${env.TAG} ./frontend"
                    sh "docker build -t ${BACKEND_IMAGE}:${env.TAG} ./backend"
                }
            }
        }

        stage('Test Applications') {
            steps {
                script {
                    sh "docker run --rm ${BACKEND_IMAGE}:${env.TAG} pytest"
                    sh """
                        docker run --rm \
                        -v ${WORKSPACE}/frontend:/app \
                        -v /app/node_modules \
                        -w /app \
                        -e CI=true \
                        node:18-alpine \
                        sh -c "npm install && timeout 5s npm test run"
                    """
                }
            }
        }

        stage('Security Scan') {
            steps {
                script {
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --severity HIGH,CRITICAL ${FRONTEND_IMAGE}:${env.TAG} || true"
                    sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --severity HIGH,CRITICAL ${BACKEND_IMAGE}:${env.TAG} || true"
                }
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: '7a839a0d-889a-4cd9-9484-443f95b911c6', 
                                                passwordVariable: 'PASS', 
                                                usernameVariable: 'USER')]) {
                    script {
                        sh "echo $PASS | docker login -u $USER --password-stdin"
                        
                        sh "docker push ${FRONTEND_IMAGE}:${env.TAG}"
                        sh "docker tag ${FRONTEND_IMAGE}:${env.TAG} ${FRONTEND_IMAGE}:latest"
                        sh "docker push ${FRONTEND_IMAGE}:latest"
                        
                        sh "docker push ${BACKEND_IMAGE}:${env.TAG}"
                        sh "docker tag ${BACKEND_IMAGE}:${env.TAG} ${BACKEND_IMAGE}:latest"
                        sh "docker push ${BACKEND_IMAGE}:latest"
                    }
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                withCredentials([file(credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {
                    script {
                        sh "kubectl --kubeconfig=${KUBECONFIG} apply -f ./kubernetes/ -R -n ${env.DEPLOYED_NS}"
                        sh "kubectl --kubeconfig=${KUBECONFIG} set image deployment/frontend-deployment frontend=${FRONTEND_IMAGE}:${env.TAG} -n ${env.DEPLOYED_NS}"
                        sh "kubectl --kubeconfig=${KUBECONFIG} set image deployment/backend-deployment backend=${BACKEND_IMAGE}:${env.TAG} -n ${env.DEPLOYED_NS}"
                    }
                }
            }
        }

        stage('Health Check') {
            steps {
                withCredentials([file(credentialsId: 'k8s-kubeconfig', variable: 'KUBECONFIG')]) {
                    script {
                        sh "kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/frontend-deployment -n ${env.DEPLOYED_NS} --timeout=90s"
                        sh "kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/backend-deployment -n ${env.DEPLOYED_NS} --timeout=90s"
                        sh "kubectl --kubeconfig=${KUBECONFIG} exec -n ${env.DEPLOYED_NS} deploy/frontend-deployment -- curl -f -s http://backend-service:5000/health/ready"
                    }
                }
            }
        }
    }

    post {
        always {
            sh "docker logout"
            cleanWs()
        }
    }
}